server :
    port : 8888

spring :
  application:
    name : config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
         # uri: https://github.com/devstudyi/spring-cloud-config
          uri: https://github.com/devstudyi/spring-cloud-config
          username : sonjs01@naver.com
          password : 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
        native:
          search-locations: file:///${user.home}/native-file-repo
management:
  endpoint:
    web:
      exposure:
        include: health, busrefresh